#数据源的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zzh1998
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,slf4j #,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#mybatis配置
mybatis:
  #设置MyBatis的配置文件（可以不用这个文件设置，可以直接在此yaml文件中设置）
  #config-location: classpath:sqlMapConfig.xml
  #设置mapper文件的位置，扫描classpath:mapper/路径下的所有mapper文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启字段驼峰模式和下划线模式的映射
    map-underscore-to-camel-case: true
  #设置cn.tx.datasource包下的所有mapper接口的别名（别名为接口的类名，大小写不区分）:
  #type-aliases-package: cn.tx.datasource
#log4j2日志配置
logging:
  #设置log4j2的配置文件
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: trace